### ISSUE TITLE
Wrong colour for repeated letter in correct place

### ISSUE THREAD

**Issue by ColonelJ** [AravindhStanley/wordle-clone-python#1]
![Screenshot from 2022-02-18 20-47-57](https://user-images.githubusercontent.com/1319508/154759639-69ef30da-3703-4d5d-82ed-3d96864db39d.png)

Any letter in the correct place should be green.

**Comment by ColonelJ** [comment]
Also, colouring behaviour isn't consistent when you do have both the repeated letters used.

![Screenshot from 2022-02-18 23-12-04](https://user-images.githubusercontent.com/1319508/154773443-74477990-d54d-454c-942e-65f39dfcb6ee.png)

**Comment by aravindh-murugesan** [comment]
Yes this looks like a bug I should handle. Thanks for pointing it out.

**Comment by aravindh-murugesan** [comment]
![image](https://user-images.githubusercontent.com/27763368/154790936-b8978323-2e15-4d18-bdc7-0842f74168eb.png)

![image](https://user-images.githubusercontent.com/27763368/154790952-8aea1a6d-500e-4c1b-9761-4f98651e840a.png)

![image](https://user-images.githubusercontent.com/27763368/154790988-9ee1c974-f5fa-402f-9a5d-9963d693e462.png)


Turns out there was a validation issue. Fixed it.
